version: '3.9'

services:

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./prescryption_backend
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=ongodb+srv://2009248:7CS82d6kPwPdNxnH@clusterprescryption.nbehj6t.mongodb.net/?retryWrites=true&w=majority&appName=clusterPrescryption
      - SECRET_KEY=prescryption_db
    depends_on:
      - mongo

  verify_service:
    build:
      context: ./prescryption_backend
      dockerfile: Dockerfile.verify
    container_name: verify_service
    ports:
      - "5000:5000"
    command: python verify_service.py

  invoice_service:
    build:
      context: ./prescryption_backend
      dockerfile: Dockerfile.invoice
    container_name: invoice_service
    ports:
      - "5005:5005"
    command: python invoice_service.py

  coverage_service:
    build:
      context: ./prescryption_backend
      dockerfile: Dockerfile.coverage
    container_name: coverage_service
    ports:
      - "5004:5004"
    command: python verify_prescription.py
  
  patient_service:
    build:
      context: ./prescryption_backend
      dockerfile: Dockerfile.patient
    container_name: patient_service
    ports:
      - "5004:5004"
    command: python verify_patient.py
  
  frontend:
    build:
      context: ./prescryption_frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  mongo-data:
